apiVersion: v1
kind: ConfigMap
metadata:
  name: k8snode-config
  namespace: k8snode-prd
  labels:
    app: k8snode
    environment: prd
data:
  NODE_ENV: "production"
  PORT: "3000"
  CORS_ORIGINS: "*"