apiVersion: v1
kind: ConfigMap
metadata:
  name: k8snode-config
  namespace: k8snode-hml
  labels:
    app: k8snode
    environment: hml
data:
  NODE_ENV: "homologation"
  PORT: "3000"
  CORS_ORIGINS: "*"