apiVersion: v1
kind: Secret
metadata:
  name: k8snode-secret
  namespace: k8snode-hml
  labels:
    app: k8snode-api
    environment: hml
type: Opaque
data:
  # JWT secret for HML environment (base64 encoded)
  # This is 'hml-jwt-secret-key-change-me' encoded in base64
  JWT_SECRET: aG1sLWp3dC1zZWNyZXQta2V5LWNoYW5nZS1tZQ==