apiVersion: v1
kind: Service
metadata:
  name: k8snode-service
  namespace: k8snode-hml
  labels:
    app: k8snode
    environment: hml
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: k8snode
    environment: hml